// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentConfig: typeof import('./../packages/component-config.tsx')['default']
    Editor: typeof import('./../packages/editor.tsx')['default']
    EditorBlock: typeof import('./../packages/editor-block.tsx')['default']
    MarkLine: typeof import('./../packages/mark-line.tsx')['default']
    Toolbar: typeof import('./../packages/toolbar.tsx')['default']
  }
}

export {}
